name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: iterative/setup-cml@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # lub inna wersja, jakiej używasz

      - name: Install Python packages (black)
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Install Project Dependencies
        run: make install

      - name: Format
        run: make format

      - name: Train
        run: make train

      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
